name: push tartiflette.io docker image
on:
  push:
    branches:
      - master
jobs:
  dockerRegistry:
    name: docker registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: docker registry
      uses: actions/docker/login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: build
      uses: ./actions-shell/
      with:
        entrypoint: make
        args: import-docs
    - name: build docker image
      uses: actions/docker/cli@master
      with:
        args: build -t tartiflette/tartiflette.io:latest .
    - name: is master
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: push
      uses: actions/docker/cli@master
      with:
        args: push tartiflette/tartiflette.io:latest
